In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [5]:
df = sns.load_dataset('fmri')
df.head()

  subject  timepoint event    region    signal
0     s13         18  stim  parietal -0.017552
1      s5         14  stim  parietal -0.080883
2     s12         18  stim  parietal -0.081033
3     s11         18  stim  parietal -0.046134
4     s10         18  stim  parietal -0.037970

In [6]:
df_cat = df[['subject', 'event', 'region']]
df_cat.head()

  subject event    region
0     s13  stim  parietal
1      s5  stim  parietal
2     s12  stim  parietal
3     s11  stim  parietal
4     s10  stim  parietal

In [8]:
df_group = df_cat.groupby('event')
df_group.describe()

      subject                  region
        count unique  top freq  count unique       top freq
event
cue       532     14   s3   38    532      2  parietal  266
stim      532     14  s13   38    532      2  parietal  266

In [9]:
df['group'] = pd.Series(df.event, dtype='category')

In [12]:
df['group'].dtype

CategoricalDtype(categories=['cue', 'stim'], ordered=False, categories_dtype=object)

In [13]:
df['group'].value_counts()

group
cue     532
stim    532
Name: count, dtype: int64

In [14]:
pd.crosstab(df['event'], df['region'])

region  frontal  parietal
event
cue         266       266
stim        266       266